# Generated by Django 2.0.4 on 2018-04-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180426_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='is_following', to='mainapp.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='mainapp.User'),
        ),
    ]
