# Generated by Django 2.0.4 on 2018-04-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180426_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_contents',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='user_wall',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wall_post', to='mainapp.User'),
        ),
    ]
